### ISSUE TITLE
Unable to download wham_noise.zip

### ISSUE THREAD

**Issue by Ashh-Z** [JorisCos/LibriMix#26]
After running the ./generate_librimix.sh storage_dir, the wham_noise directory is not being downloaded in the storage_dir. I am repeatedly facing a connection timed out error. 

Download wham_noise into storage_dir
--2024-02-09 14:01:12--  https://storage.googleapis.com/whisper-public/wham_noise.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 2404:6800:4002:804::201b, 2404:6800:4002:82e::201b, 2404:6800:4002:82f::201b, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2404:6800:4002:804::201b|:443... failed: Connection timed out.
Connecting to storage.googleapis.com (storage.googleapis.com)|2404:6800:4002:82e::201b|:443... failed: Connection timed out.
Connecting to storage.googleapis.com (storage.googleapis.com)|2404:6800:4002:82f::201b|:443... failed: Connection timed out.
Connecting to storage.googleapis.com (storage.googleapis.com)|2404:6800:4002:806::201b|:443... failed: Connection timed out.
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.207.219|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-02-09 14:09:56 ERROR 403: Forbidden.

It appears that augmented files have not been generated properly
Resuming augmentation.
Change speed with factor 0.8
0it [00:00, ?it/s]
Change speed with factor 1.2
0it [00:00, ?it/s]
Directory storage_dir/Libri2Mix/wav8k/min/train-100 already exist. Files won't be overwritten
Directory storage_dir/Libri2Mix/wav8k/max/train-100 already exist. Files won't be overwritten
Directory storage_dir/Libri2Mix/wav16k/min/train-100 already exist. Files won't be overwritten
Directory storage_dir/Libri2Mix/wav16k/max/train-100 already exist. Files won't be overwritten
Directory storage_dir/Libri2Mix/wav8k/min/dev already exist. Files won't be overwritten
Directory storage_dir/Libri2Mix/wav8k/max/dev already exist. Files won't be overwritten
Creating mixtures and sources from metadata/Libri2Mix/libri2mix_dev-clean.csv in storage_dir/Libri2Mix/wav16k/min/dev
  0%|                                                                                                                       | 0/3000 [00:00<?, ?it/s]
concurrent.futures.process._RemoteTraceback: 
"""

Traceback (most recent call last):
  File "/opt/anaconda/anaconda3/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/anaconda/anaconda3/lib/python3.7/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/opt/anaconda/anaconda3/lib/python3.7/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "scripts/create_librimix_from_metadata.py", line 159, in process_utterance
    wham_dir)
  File "scripts/create_librimix_from_metadata.py", line 249, in read_sources
    noise, _ = sf.read(noise_path, dtype='float32', stop=max_length)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/soundfile.py", line 286, in read
    subtype, endian, format, closefd) as f:
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'storage_dir/wham_noise/cv/20oo0109_0.72115_01ua010r_-0.72115.wav': System error.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/create_librimix_from_metadata.py", line 415, in <module>
    main(args)
  File "scripts/create_librimix_from_metadata.py", line 59, in main
    freqs, n_src, modes, types)
  File "scripts/create_librimix_from_metadata.py", line 72, in create_librimix
    wham_dir, out_dir, modes, types)
  File "scripts/create_librimix_from_metadata.py", line 115, in process_metadata_file
    subdirs, dir_path, subset_metadata_path, n_src)
  File "scripts/create_librimix_from_metadata.py", line 138, in process_utterances
    chunksize=10,
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tqdm/contrib/concurrent.py", line 105, in process_map
    return _executor_map(ProcessPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/opt/anaconda/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/opt/anaconda/anaconda3/lib/python3.7/concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/opt/anaconda/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/opt/anaconda/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/anaconda/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
soundfile.LibsndfileError: Error opening 'storage_dir/wham_noise/cv/20oo0109_0.72115_01ua010r_-0.72115.wav': System error.

**Comment by JorisCos** [comment]
Should be fixed now. Thanks for reporting the issue.

**Comment by Ashh-Z** [comment]
The issue persists. I am still unable to download the wham_noise.zip @JorisCos

**Comment by JorisCos** [comment]
My bad, should be ok now

**Comment by PeiwenSun2000** [comment]
The issue still persists. Has anyone solved it now?

**Comment by JorisCos** [comment]
The provided link https://my-bucket-a8b4b49c25c811ee9a7e8bba05fa24c7.s3.amazonaws.com/wham_noise.zip is still up.
